/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Keoma
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblTitle2 = new javax.swing.JLabel();
        jButtonLogout = new javax.swing.JButton();
        jButtonManageDoors = new javax.swing.JButton();
        jButtonShowHierarchy = new javax.swing.JButton();
        jLabelHierarchy = new javax.swing.JLabel();
        jLabelDoor = new javax.swing.JLabel();
        jLabelLogout = new javax.swing.JLabel();
        lblMainMenu = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(21, 25, 28));
        jPanel1.setPreferredSize(new java.awt.Dimension(881, 632));

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(169, 224, 49));
        lblTitle.setText("SECURITREE - Security Dashboard");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(lblTitle)
                .addContainerGap(237, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addContainerGap(590, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setPreferredSize(new java.awt.Dimension(920, 620));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(21, 25, 28));

        lblTitle2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(169, 224, 49));
        lblTitle2.setText("SECURITREE - Security Dashboard");

        jButtonLogout.setBackground(new java.awt.Color(152, 201, 45));
        jButtonLogout.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jButtonLogout.setForeground(new java.awt.Color(21, 25, 28));
        jButtonLogout.setText("Log Out");
        jButtonLogout.setBorder(null);
        jButtonLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLogout.setFocusPainted(false);
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jButtonManageDoors.setBackground(new java.awt.Color(152, 201, 45));
        jButtonManageDoors.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jButtonManageDoors.setForeground(new java.awt.Color(21, 25, 28));
        jButtonManageDoors.setText("Manage Doors");
        jButtonManageDoors.setBorder(null);
        jButtonManageDoors.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonManageDoors.setFocusPainted(false);
        jButtonManageDoors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageDoorsActionPerformed(evt);
            }
        });

        jButtonShowHierarchy.setBackground(new java.awt.Color(152, 201, 45));
        jButtonShowHierarchy.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jButtonShowHierarchy.setForeground(new java.awt.Color(21, 25, 28));
        jButtonShowHierarchy.setText("View Security Entity Hierarchy");
        jButtonShowHierarchy.setBorder(null);
        jButtonShowHierarchy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonShowHierarchy.setFocusPainted(false);
        jButtonShowHierarchy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowHierarchyActionPerformed(evt);
            }
        });

        jLabelHierarchy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_hierarchy_96px.png"))); // NOI18N

        jLabelDoor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_door_sensor_checked_96px.png"))); // NOI18N

        jLabelLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_exit_96px.png"))); // NOI18N

        lblMainMenu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMainMenu.setForeground(new java.awt.Color(169, 224, 49));
        lblMainMenu.setText("Main Menu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTitle2)
                        .addGap(234, 234, 234))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonShowHierarchy, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jButtonManageDoors, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabelHierarchy)
                .addGap(205, 205, 205)
                .addComponent(jLabelDoor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelLogout)
                .addGap(89, 89, 89))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(411, 411, 411)
                .addComponent(lblMainMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle2)
                .addGap(38, 38, 38)
                .addComponent(lblMainMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHierarchy, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelDoor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelLogout, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonManageDoors, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonShowHierarchy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(209, 209, 209))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        this.dispose();
        Login L = new Login();
        L.setVisible(true);
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonManageDoorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageDoorsActionPerformed
        this.dispose();
        Manage M = new Manage();
        M.setVisible(true);
    }//GEN-LAST:event_jButtonManageDoorsActionPerformed

    private void jButtonShowHierarchyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowHierarchyActionPerformed
        JavaTreeWithDB H = new JavaTreeWithDB();
        H.setVisible(true);     
        H.setSize(600,1000);
        H.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonShowHierarchyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonManageDoors;
    private javax.swing.JButton jButtonShowHierarchy;
    private javax.swing.JLabel jLabelDoor;
    private javax.swing.JLabel jLabelHierarchy;
    private javax.swing.JLabel jLabelLogout;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblMainMenu;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle2;
    // End of variables declaration//GEN-END:variables
}
